export type Tool = {
  /** Unique key used in logic & UI */
  id: string;
  /** Human‑friendly name shown in tool palette */
  label: string;
  /** Fallback emoji icon (can be replaced by sprite in the palette) */
  emoji: string;
  /** Construction cost in in‑game currency */
  cost: number;
  /** Canonical size expressed as the larger of w/h (retained for legacy APIs) */
  size: number;
  /** Index in the original Micropolis tool order */
  index: number;
  /** X position (in tiles) of the tool sprite inside the tool‑tilesheet */
  x: number;
  /** Y position (in tiles) of the tool sprite inside the tool‑tilesheet */
  y: number;
  /** Width  (in tiles)  of the tool sprite */
  w: number;
  /** Height (in tiles) of the tool sprite */
  h: number;
};

export const TOOLS: Tool[] = [
  {
    id: "residential",
    label: "Residential",
    emoji: "🏚️",
    cost: 100,
    size: 3,
    index: 0,
    x: 0,
    y: 0,
    w: 3,
    h: 3,
  },
  {
    id: "commercial",
    label: "Commercial",
    emoji: "🏢",
    cost: 100,
    size: 3,
    index: 1,
    x: 3,
    y: 0,
    w: 3,
    h: 3,
  },
  {
    id: "industrial",
    label: "Industrial",
    emoji: "🏭",
    cost: 100,
    size: 3,
    index: 2,
    x: 6,
    y: 0,
    w: 3,
    h: 3,
  },
  {
    id: "fire-station",
    label: "Fire Station",
    emoji: "🚒",
    cost: 500,
    size: 3,
    index: 3,
    x: 0,
    y: 3,
    w: 3,
    h: 3,
  },
  {
    id: "police-station",
    label: "Police Station",
    emoji: "🚓",
    cost: 500,
    size: 3,
    index: 4,
    x: 3,
    y: 3,
    w: 3,
    h: 3,
  },
  {
    id: "inspect",
    label: "Inspect",
    emoji: "🔎",
    cost: 0,
    size: 1,
    index: 5,
    x: 6,
    y: 3,
    w: 1,
    h: 1,
  },
  {
    id: "wire",
    label: "Wire",
    emoji: "🔌",
    cost: 5,
    size: 1,
    index: 6,
    x: 7,
    y: 3,
    w: 1,
    h: 1,
  },
  {
    id: "bulldozer",
    label: "Bulldozer",
    emoji: "🚜",
    cost: 1,
    size: 1,
    index: 7,
    x: 8,
    y: 3,
    w: 1,
    h: 1,
  },
  {
    id: "railroad",
    label: "Railroad",
    emoji: "🚂",
    cost: 20,
    size: 1,
    index: 8,
    x: 6,
    y: 4,
    w: 1,
    h: 1,
  },
  {
    id: "road",
    label: "Road",
    emoji: "🚗",
    cost: 10,
    size: 1,
    index: 9,
    x: 7,
    y: 4,
    w: 1,
    h: 1,
  },
  {
    id: "stadium",
    label: "Stadium",
    emoji: "🏟️",
    cost: 5000,
    size: 4,
    index: 10,
    x: 0,
    y: 6,
    w: 4,
    h: 4,
  },
  {
    id: "park",
    label: "Park",
    emoji: "🌴",
    cost: 10,
    size: 1,
    index: 11,
    x: 8,
    y: 4,
    w: 1,
    h: 1,
  },
  {
    id: "seaport",
    label: "Seaport",
    emoji: "🚢",
    cost: 3000,
    size: 4,
    index: 12,
    x: 4,
    y: 6,
    w: 4,
    h: 4,
  },
  {
    id: "coal-power",
    label: "Coal Power",
    emoji: "🔋",
    cost: 3000,
    size: 4,
    index: 13,
    x: 0,
    y: 10,
    w: 4,
    h: 4,
  },
  {
    id: "nuclear-power",
    label: "Nuclear Power",
    emoji: "☢️",
    cost: 5000,
    size: 4,
    index: 14,
    x: 4,
    y: 10,
    w: 4,
    h: 4,
  },
  {
    id: "airport",
    label: "Airport",
    emoji: "✈️",
    cost: 10000,
    size: 6,
    index: 15,
    x: 0,
    y: 14,
    w: 6,
    h: 6,
  },
  // num 16 was reserved for a deprecated "network" tool; skipping duplicate sprite (7,3)
  {
    id: "water",
    label: "Water",
    emoji: "💧",
    cost: 0,
    size: 1,
    index: 17,
    x: 6,
    y: 5,
    w: 1,
    h: 1,
  },
  {
    id: "land",
    label: "Land",
    emoji: "⛰️",
    cost: 0,
    size: 1,
    index: 18,
    x: 7,
    y: 5,
    w: 1,
    h: 1,
  },
  {
    id: "forest",
    label: "Forest",
    emoji: "🌳",
    cost: 0,
    size: 1,
    index: 19,
    x: 8,
    y: 5,
    w: 1,
    h: 1,
  },
];
